services:
  - type: web
    name: pokesale
    runtime: python
    buildCommand: python -m py_compile app.py
    startCommand: python -u app.py
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: SCAN_MINUTES
        value: 15
      - key: PYTHONUNBUFFERED
        value: "1"
